version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db

    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: advisor
      MYSQL_PASSWORD: root

    ports: 
      - "6033:3306" 

    volumes:
      - ./data/db:/var/lib/mysql

  myapp:
    image: docker.io/bitnami/laravel:8
    command: composer update
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=advisor
      - DB_PASSWORD=my_secret_password

    volumes:
      - './my-project:/app'
    depends_on:
      - db
